- README.md
Github issues aren't active, so I created a JIRA account which apparently doesn't have permissions to create issues.
alternatively, enable github issues
> Add link to community forum

- build.gradle
Update sonar-scanner-api to version 2.12
> SONARGRADL-55 update sonar-scanner-api

- src/main/java/org/sonarqube/gradle/SonarQubePlugin.java
Additionally clear the map when the build finishes
> Clear the actionBroadcastMap once build finishes

- build.gradle
> Fix repositories URLs

- build.gradle
Please review our [contribution guidelines](https://github.com/SonarSource/sonar-scanner-gradle/blob/master/contributing.md).
And please ensure your pull request adheres to the following guidelines:
> Add the SonarSource Team as a developer

- integrationTests/docker/Dockerfile
- integrationTests/docker/Dockerfile_java11
- src/test/groovy/org/sonarqube/gradle/FunctionalTests.groovy
> Switch base image for cirrus runs

- .cirrus.yml
> Fix build using Java 11 with Next

- .cirrus.yml
- build.gradle
> BUILD-915 Sign artifacts

- .cirrus.yml
- build.gradle
- gradle.properties
BUILD-1449: use org.cyclonedx.bom Gradle plugin to generate a SBOM artifact attached to the build
> BUILD-1449 sbom plugin

- .cirrus.yml
> BUILD-1744 fix jfrog

- src/main/java/org/sonarqube/gradle/SonarQubePlugin.java
Avoid multiple computations of the properties, which may result in repeated logging.
> SONARGRADL-90 Use the ProviderAPI to allow lazy configuration

- .cirrus.star
- .cirrus.yml
- integrationTests/docker/Dockerfile
- integrationTests/docker/Dockerfile_java11
- integrationTests/docker/Dockerfile_java17
> BUILD-2280 Migrate to CirrusCI on AWS

- gradle.properties
- integrationTests/pom.xml
> Prepare for the next development iteration

- src/main/java/org/sonarqube/gradle/AndroidUtils.java
- src/main/java/org/sonarqube/gradle/SonarPropertyComputer.java
* duplications
* unused imports
* unused method parameters
* add Nullable annotation
> Fix quality flaw:

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/PullRequestClosed.yml
- .github/workflows/PullRequestCreated.yml
- .github/workflows/RequestReview.yml
- .github/workflows/SubmitReview.yml
[SCANGRADLE-160](https://sonarsource.atlassian.net/browse/SCANGRADLE-160)
To review:
Make sure the files are the same as these
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml
https://raw.githubusercontent.com/SonarSource/sonar-dotnet-enterprise/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md?token=GHSAT0AAAAAACM3Q6EYDU5DNCGFOFCNBMAYZYSOQXA
Make sure that PullRequestCreated.yml has the correct Jira project on the last …
> SCANGRADLE-160 Add Jira integration

- gradle.properties
- integrationTests/pom.xml
[SCANGRADLE-173](https://sonarsource.atlassian.net/browse/SCANGRADLE-173)
[SCANGRADLE-173]: https://sonarsource.atlassian.net/browse/SCANGRADLE-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-173 Bump to major version 6.0

- src/test/groovy/org/sonarqube/gradle/FunctionalTests.groovy
- src/test/groovy/org/sonarqube/gradle/SonarQubePluginTest.groovy
- src/test/java/org/sonarqube/gradle/SourceCollectorTest.java
[SCANGRADLE-176](https://sonarsource.atlassian.net/browse/SCANGRADLE-176)
Part of MMF-4135
[SCANGRADLE-176]: https://sonarsource.atlassian.net/browse/SCANGRADLE-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-176 Fix unit tests on Windows

- src/main/resources/static/documentation.md
[SCANGRADLE-177](https://sonarsource.atlassian.net/browse/SCANGRADLE-177)
Part of MMF-4135
[SCANGRADLE-177]: https://sonarsource.atlassian.net/browse/SCANGRADLE-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-177 Add static documentation

- .cirrus.star
[SCANGRADLE-179](https://sonarsource.atlassian.net/browse/SCANGRADLE-179)
[SCANGRADLE-179]: https://sonarsource.atlassian.net/browse/SCANGRADLE-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-179 Upgrade cirrus-modules to v3

- integrationTests/src/test/resources/multi-module-android-studio-lint/app/build.gradle
- integrationTests/src/test/resources/multi-module-android-studio-lint/app2/build.gradle
- integrationTests/src/test/resources/multi-module-android-studio-lint/app3/build.gradle
- integrationTests/src/test/resources/multi-module-android-studio-lint/app4/build.gradle
[SCANGRADLE-163](https://sonarsource.atlassian.net/browse/SCANGRADLE-163)
[SCANGRADLE-163]: https://sonarsource.atlassian.net/browse/SCANGRADLE-163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-163 set android sdk to 33 in module android studio lint project inorder to fix ITs

- integrationTests/src/test/java/org/sonarqube/gradle/AbstractGradleIT.java
- integrationTests/src/test/java/org/sonarqube/gradle/AndroidTest.java
- integrationTests/src/test/resources/kotlin-jvm-submodule/gradlew.bat
- integrationTests/src/test/resources/kotlin-jvm/gradlew.bat
[SCANGRADLE-180](https://sonarsource.atlassian.net/browse/SCANGRADLE-180)
Part of MMF-4135
[SCANGRADLE-180]: https://sonarsource.atlassian.net/browse/SCANGRADLE-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-180 Fix ITs on Windows

- .github/workflows/mark-prs-stale.yml
[SCANGRADLE-186](https://sonarsource.atlassian.net/browse/SCANGRADLE-186)
> SCANGRADLE-186 Add automation to mark and close stale PRs

- gradle.properties
- integrationTests/pom.xml
[SCANGRADLE-188](https://sonarsource.atlassian.net/browse/SCANGRADLE-188)
[SCANGRADLE-188]: https://sonarsource.atlassian.net/browse/SCANGRADLE-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-188 Prepare next development iteration 6.1

- gradle.properties
[SCANGRADLE-191](https://sonarsource.atlassian.net/browse/SCANGRADLE-191)
[SCANGRADLE-191]: https://sonarsource.atlassian.net/browse/SCANGRADLE-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-191 Prepare next development iteration 6.0.1

- sonarqube-build.gradle.kts
[SCANGRADLE-198](https://sonarsource.atlassian.net/browse/SCANGRADLE-198)
[SCANGRADLE-198]: https://sonarsource.atlassian.net/browse/SCANGRADLE-198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-198 Upgrade scanner to version 6.0.1.5171

- sonarqube-build.gradle.kts
[SCANGRADLE-199](https://sonarsource.atlassian.net/browse/SCANGRADLE-199)
[SCANGRADLE-199]: https://sonarsource.atlassian.net/browse/SCANGRADLE-199?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-199 The Gradle scanner should utilize a recent version of itself for self-analysis

- build.gradle.kts
- integrationTests/src/test/java/org/sonarqube/gradle/BootstrapTest.java
- integrationTests/src/test/java/org/sonarqube/gradle/GradleTest.java
- src/main/java/org/sonarqube/gradle/SonarTask.java
- src/test/groovy/org/sonarqube/gradle/FunctionalTests.groovy
[SCANGRADLE-201](https://sonarsource.atlassian.net/browse/SCANGRADLE-201)
[SCANGRADLE-201]: https://sonarsource.atlassian.net/browse/SCANGRADLE-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-201 bump sonar-scanner-java-library to 3.1.1.261

- .cirrus.yml
[SCANGRADLE-204](https://sonarsource.atlassian.net/browse/SCANGRADLE-204)
[SCANGRADLE-204]: https://sonarsource.atlassian.net/browse/SCANGRADLE-204?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-204 add Gradle 8.13 to ITs matrix

- src/main/java/org/sonarqube/gradle/SonarTask.java
[SCANGRADLE-201](https://sonarsource.atlassian.net/browse/SCANGRADLE-201)
[SCANGRADLE-201]: https://sonarsource.atlassian.net/browse/SCANGRADLE-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-201 warp engine facade in try with-resources

- build.gradle.kts
- src/test/groovy/org/sonarqube/gradle/FunctionalTests.groovy
[SCANGRADLE-200](https://sonarsource.atlassian.net/browse/SCANGRADLE-200)
[SCANGRADLE-200]: https://sonarsource.atlassian.net/browse/SCANGRADLE-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-200 Add support for SonarQube Cloud regions

- gradle.properties
- integrationTests/pom.xml
[SCANGRADLE-212](https://sonarsource.atlassian.net/browse/SCANGRADLE-212)
[SCANGRADLE-212]: https://sonarsource.atlassian.net/browse/SCANGRADLE-212?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-212 Prepare next development iteration 6.2

- integrationTests/src/test/java/org/sonarqube/gradle/AbstractGradleIT.java
- src/main/java/org/sonarqube/gradle/AndroidUtils.java
- src/main/java/org/sonarqube/gradle/SonarPropertyComputer.java
- src/main/java/org/sonarqube/gradle/SonarUtils.java
- src/test/groovy/org/sonarqube/gradle/SonarUtilsTest.java
[SCANGRADLE-135](https://sonarsource.atlassian.net/browse/SCANGRADLE-135)
[SCANGRADLE-135]: https://sonarsource.atlassian.net/browse/SCANGRADLE-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-135 Replace deprecated APIs

- .github/workflows/releasability.yaml
[SCANGRADLE-236](https://sonarsource.atlassian.net/browse/SCANGRADLE-236)
[SCANGRADLE-236]: https://sonarsource.atlassian.net/browse/SCANGRADLE-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-236 Update releasability-status action to v2

- .github/workflows/PrepareNextIteration.yml
[SCANGRADLE-251](https://sonarsource.atlassian.net/browse/SCANGRADLE-251)
[SCANGRADLE-251]: https://sonarsource.atlassian.net/browse/SCANGRADLE-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-251: Generate unique branch name

- .gitattributes
[SCANGRADLE-258](https://sonarsource.atlassian.net/browse/SCANGRADLE-258)
[SCANGRADLE-258]: https://sonarsource.atlassian.net/browse/SCANGRADLE-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-258 Remove .gitattributes that introduce more problems than solution

- .cirrus.yml
- sonarqube-build.gradle.kts
[SCANGRADLE-259](https://sonarsource.atlassian.net/browse/SCANGRADLE-259)
[SCANGRADLE-259]: https://sonarsource.atlassian.net/browse/SCANGRADLE-259?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANGRADLE-259 Exclude integration tests from SCA analysis

- src/main/java/org/sonarqube/gradle/SonarQubePlugin.java
- src/main/java/org/sonarqube/gradle/SonarResolverTask.java
- src/main/java/org/sonarqube/gradle/SonarTask.java
- src/main/java/org/sonarqube/gradle/SonarUtils.java
- src/test/java/org/sonarqube/gradle/SonarTaskTest.java
- src/test/java/org/sonarqube/gradle/SonarUtilsTest.java
[SCANGRADLE-271](https://sonarsource.atlassian.net/browse/SCANGRADLE-271)
Part of 
Thank You!
[SCANGRADLE-271]: …
> SCANGRADLE-271 Compute correct property key for libraries properties

- integrationTests/src/test/java/org/sonarqube/gradle/AbstractGradleIT.java
- src/main/java/org/sonarqube/gradle/SonarQubePlugin.java
- src/main/java/org/sonarqube/gradle/SonarResolverTask.java
- src/main/java/org/sonarqube/gradle/SonarUtils.java
- src/test/groovy/org/sonarqube/gradle/FunctionalTests.groovy
- src/test/java/org/sonarqube/gradle/SonarUtilsTest.java
[SCANGRADLE-279](https://sonarsource.atlassian.net/browse/SCANGRADLE-279)
Part of 
Thank You!
[SCANGRADLE-279]: …
> SCANGRADLE-279 Resolve classpath at execution time

- src/main/java/org/sonarqube/gradle/SonarQubePlugin.java
- src/main/java/org/sonarqube/gradle/SonarResolverTask.java
[SCANGRADLE-281](https://sonarsource.atlassian.net/browse/SCANGRADLE-281)
Part of 
Thank You!
[SCANGRADLE-281]: …
> SCANGRADLE-281 Add task description and group to SonarResolverTask
