build.gradle

Systems like Windows use cp1252 as default, so javadoc can not be generated, which failes the build.
This PR enforces UTF-8 for source files and javadoc generation

enforce UTF-8 encoding

---

src/main/java/org/sonarqube/gradle/SonarQubePlugin.java

Fixed 'sonar.libraries' population: library paths were incorrectly being added as a single property, resulting in exceptions during the sonar run as the following:
```
Caused by: java.lang.IllegalStateException: No files nor directories matching '[/path/to/home/.gradle/caches/modules-2/files-2.1/com.example/some-library/1.0/7a885b1624285ea1a7b91fbd31040554a6385a10/some-library-1.0.jar' in directory /path/to/home/my-project
at org.sonar.batch.scan.ProjectReactorBuilder.validateDirectories(ProjectReactorBuilder.java:302)
```

Fixed 'sonar.libraries' property population

---

src/main/java/org/sonarqube/gradle/AndroidUtils.java

Added filtering for classpath entries to keep only the ones which are available on the file system. This is needed to make sure that the sonar.java[.test].libraries properties contain only valid entries.
Otherwise an java.lang.IllegalStateException is thrown, i.e. for `{project.buildDir}/intermediates/dependency-cache/{variantName}`
```
+ ./gradlew -v
------------------------------------------------------------
Gradle 3.3
------------------------------------------------------------
Build time:   2017-01-03 15:31:04 UTC
Revision:     075893a3d0798c0c1f322899b41ceca82e4e134b
Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_45 (Oracle Corporation 25.45-b02)
OS:           Linux 3.10.0-229.11.1.el7.x86_64 amd64 …
```

Filter 'sonar.java[.test].libraries' to only valid entries

---

build.gradle

Prior to Jacoco 0.8.0, there was no way to filter out lombok generated code from test coverage with Jacoco. This makes it very hard to get accurate test coverage reporting in sonarqube. In a project I am working on, there's a 30% discrepancy between reported LoC in jacoco itself and sonarqube. Updating to 0.8.0 should alleviate this issue. Context: https://github.com/jacoco/jacoco/pull/513#issuecomment-293176354
Please consider making this update!

Updates jacoco to 0.8.0

---

src/main/java/org/sonarqube/gradle/SonarPropertyComputer.java
src/main/java/org/sonarqube/gradle/SonarQubePlugin.java

This PR alleviates a memory leak around `SonarQubePlugin#actionBroadcastMap`.
The problem was reported here: https://community.sonarsource.com/t/memory-leaks-in-sonarqube-gradle-plugin-2-7-and-2-6-2/6165
This PR does not fully fix the issue, but improves upon the current situation by changing the map lookup key to the project name, instead of the full gradle projects.
This enables the gradle daemon to become memory stable again in our development environment.

Improvement to memory leak concerning SonarQubePlugin#actionBroadcastMap

---

src/main/java/org/sonarqube/gradle/SonarQubePlugin.java
src/test/groovy/org/sonarqube/gradle/SonarQubePluginTest.groovy

In Gradle, tasks can be inserted into groups. Tasks that have a group are already displayed by executing `/gradlew tasks`, while tasks without a group are only displayed by executing `/gradlew tasks --all`.
I have implemented that the task is added to the `Verification` group and also adapted the JUnit test to validate this.
I hope, since this is a trivial beauty change, that a pull request will suffice.

Add group to `sonarqube` task

---

build.gradle

Fix based on a workaround for this issue: https://github.com/gradle/gradle/issues/16603

Add sleep add the end of the gradle execution as a workaround on zipping cache issue

---

.cirrus.yml

See https://community.sonarsource.com/t/gradle-7-5-not-working-with-gradle-sonarqube-plugin-3-4-0-2513/69189.

Run ITs with Gradle 7.5.1

---

README.md

The other way also works (it's the old way of applying plugins), but it required also to use a `buildscript` block to include the plugin in the classpath.

[NO JIRA] Fix README regarding using composite builds

---

src/main/java/org/sonarqube/gradle/SonarExtension.java

Change in Java: https://bugs.openjdk.org/browse/JDK-8220379
Otherwise the build fails with message:
`C:\me\git\sonar-scanner-gradle\src\main\java\org\sonarqube\gradle\SonarExtension.java:40: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>
`

NO-JIRA fixed an issue where building a project failed on JDK >= 13

---

.cirrus.yml
cirrus/cirrus-qa.sh
gradle/wrapper/gradle-wrapper.properties
integrationTests/src/test/java/org/sonarqube/gradle/AbstractGradleIT.java
integrationTests/src/test/java/org/sonarqube/gradle/AndroidTest.java
src/main/java/org/sonarqube/gradle/SonarPropertyComputer.java

1. I've tried introducing some test for SonarPropertyComputer (doesn't have any test yet) and I failed. Since we are relying heavily on reflection and Gradle version - it is not so easy to test.
2. Android Gradle Plugin 7.x is not compatible with Gradle 8. Android Gradle Plugin 8.x is not released yet. 
https://mvnrepository.com/artifact/com.android.tools.build/gradle?repo=google
So if we merge this PR in its current form we would need to add a ticket to bump AGP when they release it (and add IT for it).

Support Gradle 8

---

build.gradle.kts

Fixes an issue where we no longer generated coverage data because the upstream build script changed task from `sonarqube` to `sonar`.

Change task name

---

gradle.properties
integrationTests/pom.xml
src/main/java/org/sonarqube/gradle/SonarQubePlugin.java
src/test/groovy/org/sonarqube/gradle/FunctionalTests.groovy
src/test/groovy/org/sonarqube/gradle/SonarQubePluginTest.groovy

Rename the parameter so that its name carries its Gradle specificity. This should make it clearer that this parameter is not meant to be supported by other scanners.

SONARGRADL-132 Rename parameter `sonar.skipCompile` to `sonar.gradle.skipCompile`

---

src/main/java/org/sonarqube/gradle/SonarPropertyComputer.java
src/test/groovy/org/sonarqube/gradle/GradleKtsTests.groovy
src/test/groovy/org/sonarqube/gradle/SonarQubePluginTest.groovy

Child modules copy the "sonar.tests" property from the parent when it is not defined. This behavior is encoded in the scanner engine, and it breaks the logic defined in [SCANGRADLE-152](https://sonarsource.atlassian.net/browse/SCANGRADLE-152) causing doubled indexing.
[SCANGRADLE-152]: https://sonarsource.atlassian.net/browse/SCANGRADLE-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-152 Fix issue with "sonar.tests" in child modules

---

.github/workflows/releasability.yaml

No need for conditions, as we only trigger this manually.

Remove conditions from manually-triggered releasability check

---

.cirrus.yml

[SCANGRADLE-178](https://sonarsource.atlassian.net/browse/SCANGRADLE-178)
[SCANGRADLE-178]: https://sonarsource.atlassian.net/browse/SCANGRADLE-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-163 enable gradle version 7.5.1 in ITs

---

.cirrus.yml
integrationTests/pom.xml
integrationTests/src/test/java/org/sonarqube/gradle/AndroidTest.java

[SCANGRADLE-162](https://sonarsource.atlassian.net/browse/SCANGRADLE-162)
[SCANGRADLE-162]: https://sonarsource.atlassian.net/browse/SCANGRADLE-162?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-162 Restore ITs using the Android Gradle Plugin

---

src/main/java/org/sonarqube/gradle/SonarQubePlugin.java

[SCANGRADLE-158](https://sonarsource.atlassian.net/browse/SCANGRADLE-158)
[SCANGRADLE-158]: https://sonarsource.atlassian.net/browse/SCANGRADLE-158?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-158 Lazily register sonar and sonarqube tasks

---

.cirrus.yml

[SCANGRADLE-185](https://sonarsource.atlassian.net/browse/SCANGRADLE-185)
cirrus-modules@v3 provides this configuration and it should not be configured in the project itself.
[SCANGRADLE-185]: https://sonarsource.atlassian.net/browse/SCANGRADLE-185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-185 Remove subnet-related config from .cirrus.yml

---

.cirrus.yml
build.gradle.kts

[SCANGRADLE-192](https://sonarsource.atlassian.net/browse/SCANGRADLE-192)
[SCANGRADLE-192]: https://sonarsource.atlassian.net/browse/SCANGRADLE-192?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-192 External contributor can’t build sonar-scanner-gradle plugin

---

.cirrus.yml
settings.gradle.kts

[SCANGRADLE-193](https://sonarsource.atlassian.net/browse/SCANGRADLE-193)
Part of SONARJAVA-5243
[SCANGRADLE-193]: https://sonarsource.atlassian.net/browse/SCANGRADLE-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-193 Onboard Develocity

---

build.gradle.kts

[SCANGRADLE-209](https://sonarsource.atlassian.net/browse/SCANGRADLE-209)
Logging is done by the most recent version of the sonar-scanner-java-library.
[SCANGRADLE-209]: https://sonarsource.atlassian.net/browse/SCANGRADLE-209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-209 Log the SonarQube Cloud Region

---

integrationTests/pom.xml
integrationTests/src/test/java/org/sonarqube/gradle/BootstrapTest.java

[SCANGRADLE-216](https://sonarsource.atlassian.net/browse/SCANGRADLE-216)
This is to avoid polluting telemetry data with integration tests.
[SCANGRADLE-216]: https://sonarsource.atlassian.net/browse/SCANGRADLE-216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-216 Update orchestrator dependency to version 5.5

---

.cirrus.yml

[SCANGRADLE-227](https://sonarsource.atlassian.net/browse/SCANGRADLE-227)
[SCANGRADLE-227]: https://sonarsource.atlassian.net/browse/SCANGRADLE-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-227 Fix cirrus-ci depends_on error

---

README.md

[SCANGRADLE-230](https://sonarsource.atlassian.net/browse/SCANGRADLE-230)
document the process to validate a new dependency inside the `gradle/verification-metadata.xml` file
[SCANGRADLE-230]: https://sonarsource.atlassian.net/browse/SCANGRADLE-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-230 add a new paragraph to the readme about gradle metadata validation

---

src/main/java/org/sonarqube/gradle/SonarUtils.java
src/test/groovy/org/sonarqube/gradle/SonarUtilsGroovyTest.java
src/test/java/org/sonarqube/gradle/SonarUtilsTest.java

[SCANGRADLE-249](https://sonarsource.atlassian.net/browse/SCANGRADLE-249)
[SCANGRADLE-249]: https://sonarsource.atlassian.net/browse/SCANGRADLE-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-249 Release version 6.3.0.5676 fails with ClassCastException: String cannot be cast to class Collection

---

src/main/java/org/sonarqube/gradle/SonarPropertyComputer.java
src/test/groovy/org/sonarqube/gradle/SonarQubePluginTest.groovy

[SCANGRADLE-252](https://sonarsource.atlassian.net/browse/SCANGRADLE-252)
[SCANGRADLE-252]: https://sonarsource.atlassian.net/browse/SCANGRADLE-252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SCANGRADLE-252 ".github" folder should not be added to "sonar.sources" if the user explicitly overrides this property
